### ISSUE TITLE
Set up python and its package manager

### ISSUE THREAD

**Issue by AnhChienVu** [gitdevjin/code-mage#1]
Since I don’t typically work with Python, there are a few additional setup steps that may require more detailed instructions to avoid issues during installation.

For example, in Step 2 of the installation process, users may encounter an error when trying to run pipx install poetry. This occurs because pipx needs to be installed first. To prevent this, I recommend adding the following instructions to the README:
1. Install pipx: Open a terminal and run the following command:
    python -m pip install --user pipx
2. Add pipx to PATH: Run this command to ensure pipx is added to your PATH:
    python -m pipx ensurepath
3. Restart Terminal: Close and reopen the terminal to apply the changes.

**Comment by gitdevjin** [comment]
That's a great feedback! I will fix it soon
