### ISSUE TITLE
Keep the translated source code separate with the original one

### ISSUE THREAD

**Issue by AnhChienVu** [gitdevjin/code-mage#2]
After translating the code into another language, there's no need to include the original code again in the documentation. You can simply provide the translated version. For users, especially when dealing with large source code files, having to scroll through the original code to reach the translation can be cumbersome. Keeping the translated code separate and easily accessible will improve usability and readability.

**Comment by gitdevjin** [comment]
Does it leave original code in the output file? I think It's only printing in the console. this was just for me checking the result. I think the output file wouldn't have the original code I guess. Could you double check it?
