### ISSUE TITLE
Cannot input multiple files as arguements

### ISSUE THREAD

**Issue by AnhChienVu** [gitdevjin/code-mage#3]
When I try to process multiple source files then your app returns error:
     poetry run codemage ./code_mage/codeMage.py ./code_mage/test.py -t java               
     usage: codemage.cmd [-h] [--target TARGET] [--output OUTPUT] source_file
     codemage.cmd: error: unrecognized arguments: ./code_mage/test.py

So, I think you can check again when you process files, maybe you can use iteration to loop through all the input files. But so far, it makes sense for me that if I want to convert 1 source file to another language, but it would be faster if I can convert multiple files.

**Comment by gitdevjin** [comment]
Yes it is currently not supporting translation of multiple file... Sorry! I will update them soon

**Comment by gitdevjin** [comment]
Now it is working for multiple file inputs
