### ISSUE TITLE
Adding a feature: --model flag option

### ISSUE THREAD

**Issue by arilloid** [gitdevjin/code-mage#9]
## Description 

Allow the user to specify the model to use with the `--model` or `-m` flag. 
This could be helpful, as the default model doesn't allow the users to track the token usage information (it doesn't seem to pass the completion token details in the response). 

## Implementation
Implementing the feature would require parsing the `--model`/`-m` option flag argument from the command line and using it instead of the default model inside the API call.

**Comment by gitdevjin** [comment]
Thanks! I updated `--model, -m` feature
